[package]
name = "pg0137_db_insert"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "25.0.1"cargo 
backtrace = "0.3.73"
chrono = "0.4.38"
confy = "0.6.1"
csv = "1.3.0"
flexi_logger = "0.28.5"
log = "0.4.21"
serde = "1.0.203"
serde_derive = "1.0.203"