version: '3.8'

services:
  mysql:
    build: .
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
