version: '3.8'

services:
  mysql:
    build: .
    container_name: uriagedb_container
    environment:
      MYSQL_ROOT_PASSWORD: p0kap0ka
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  