[package]
name = "tr0013_sales_add"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = "0.3.73"
chrono = "0.4.38"
confy = "0.6.1"
csv = "1.3.0"
flexi_logger = "0.28.5"
log = "0.4.21"
mysql = "25.0.1"
serde = "1.0.203"
serde_derive = "1.0.203"
